---
- name: Postgresql apt repository key
  become: True
  apt_key: url='https://www.postgresql.org/media/keys/ACCC4CF8.asc'

- name: Postgresql apt repository
  become: True
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{postgres_distribution_release}}-pgdg main' state=present update_cache=yes

- name: Install postgresql
  become: True
  apt: name=postgresql-{{postgresql_version}} default_release={{postgres_distribution_release}}-pgdg state=latest update_cache=yes cache_valid_time=600

- name: Install libpq-dev
  become: True
  apt: name=libpq-dev state=latest update_cache=yes cache_valid_time=600

- name: Install check-postgres
  become: True
  apt: name=check-postgres state=latest update_cache=yes cache_valid_time=600
