- hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ansible_os_family}}

- name: Default provisioning task
  hosts: all
  gather_facts: False
  roles:
    - apt_config
    - {role: install_packages, tags: ['packages']}
    - {role: git, tags: ['git']}
    - java
    - {role: golang, tags: ['go', 'golang']}
    - rvm
    - {role: nodejs, tags: ['nodejs', 'node']}
    - {role: google-cloud-sdk, tags: ['google-cloud-sdk']}
    - {role: android, tags: ['android']}
    - postgresql
    - {role: vim, tags: ['vim']}
    - {role: docker, tags: ['docker']}
    - google_chrome
    #- hipchat
    - {role: user_config, tags: ['user_config']}
    #- lilyterm
    - {role: ubuntu_config, tags: ['ubuntu_config']}
    - {role: virtualbox, tags: ['virtualbox']}
    - {role: vagrant, tags: ['vagrant']}
    - mkusb #better usb startup disk creator: https://help.ubuntu.com/community/mkusb
    - {role: caffeine, tags: ['caffeine']}
    - {role: xbindkeys, tags: ['xbindkeys']}
    - {role: indicator-multiload, tags: ['indicator-multiload']}
    - {role: updf, tags: ['updf']}
    - {role: yubikey, tags: ['yubikey']}
    - {role: remmina, tags: ['remmina']}
    - {role: seafile-client, tags: ['seafile-client']}
    - {role: generic_colorizer, tags: ['grc']}
    #- {role: autofs_client, tags: ['autofs_client']}

- name: Ping hosts
  hosts: ping
  gather_facts: False

  roles:
    - ping
