- hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ansible_os_family}}

- name: Default provisioning task
  hosts: all
  gather_facts: False
  roles:
    - apt_config
    - install_packages
    - git
    - java
    - golang
    - rvm
    - nodejs
    - {role: android, tags: ['android']}
    - postgresql
    - {role: vim, tags: ['vim']}
    - {role: docker, tags: ['docker']}
    - google_chrome
    #- hipchat
    - user_config
    #- lilyterm
    - ubuntu_config
    - {role: virtualbox, tags: ['virtualbox']}
    - mkusb #better usb startup disk creator: https://help.ubuntu.com/community/mkusb
    - {role: caffeine, tags: ['caffeine']}
    - {role: updf, tags: ['updf']}
    #- {role: autofs_client, tags: ['autofs_client']}

- name: Ping hosts
  hosts: ping
  gather_facts: False

  roles:
    - ping
