---
- name: Install dependencies
  become: True
  apt: name={{item}} state=latest
  with_items:
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - libc6:i386
    - libncurses5:i386
    - libstdc++6:i386
    - lib32z1
    - libbz2-1.0:i386

- name: Add current user to libvirtd
  become: True
  user: name={{ansible_user}} groups={{item}} append=yes
  ignore_errors: True
  with_items:
    - libvirt
    - libvirtd

- name: Add ANDROID_HOME environment variable
  lineinfile: dest=~/.bashrc line='export ANDROID_HOME=~/Android/Sdk'

- name: Add appropriate paths
  lineinfile: dest=~/.bashrc line='export PATH=$PATH:~/Android/Sdk/platform-tools:~/Android/Sdk/tools'
