---
- name: Google cloud apt repository key
  become: True
  apt_key: url='https://packages.cloud.google.com/apt/doc/apt-key.gpg'

- name: Kubernetes repository
  become: True
  apt_repository: repo="deb https://apt.kubernetes.io/ kubernetes-{{kubernetes_distribution_release}} main" state=present update_cache=yes

- name: Install kubectl
  become: True
  apt: name=kubectl state=latest

- name: Install minikube bash completions
  become: True
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl

- shell: dpkg-query --showformat='${Version}' --show minikube
  ignore_errors: True
  register: minikube_installed_version

- name: Download minikube deb
  when: minikube_version != minikube_installed_version.stdout
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube_{{minikube_version}}.deb
    dest: /tmp/minikube.deb

- name: Install minikube deb
  become: True
  when: minikube_version != minikube_installed_version.stdout
  apt: deb=/tmp/minikube.deb force=True

- name: Install minikube bash completions
  become: True
  shell: minikube completion bash > /etc/bash_completion.d/minikube

- shell: helm version | sed 's/.*v\([0-9\.]\+\).*/\1/g'
  ignore_errors: True
  register: helm_installed_version

- name: Download helm
  when: helm_version != helm_installed_version.stdout
  get_url:
    url: "https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz"
    dest: /tmp/helm.tar.gz

- name: Temp dir for helm
  when: helm_version != helm_installed_version.stdout
  file:
    path: /tmp/helm
    state: directory

- name: Unpack helm
  when: helm_version != helm_installed_version.stdout
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
    remote_src: yes

- name: Copy helm to /usr/local/bin
  become: True
  when: helm_version != helm_installed_version.stdout
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: 0755
    owner: root
    group: root
