---
- name: Google cloud apt repository key
  become: True
  apt_key: url='https://packages.cloud.google.com/apt/doc/apt-key.gpg'

- name: Kubernetes repository
  become: True
  apt_repository: repo="deb https://apt.kubernetes.io/ kubernetes-{{kubernetes_distribution_release}} main" state=present update_cache=yes

- name: Install kubectl
  become: True
  apt: name=kubectl state=latest

- name: Install kubectl bash completions
  become: True
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl

- shell: minikube version | head -n 1 | sed 's/.*v\([0-9\.]\+\).*/\1/g'
  #shell: dpkg-query --showformat='${Version}' --show minikube
  ignore_errors: True
  register: minikube_installed_version

- name: Install minikube
  become: True
  when: minikube_version != minikube_installed_version.stdout
  shell: curl -Lo /tmp/minikube https://github.com/kubernetes/minikube/releases/download/v{{minikube_version}}/minikube-linux-amd64 && chmod +x /tmp/minikube && mv /tmp/minikube /usr/local/bin

- name: Install minikube bash completions
  become: True
  when: minikube_version != minikube_installed_version.stdout
  shell: minikube completion bash > /etc/bash_completion.d/minikube

- shell: helm version | sed 's/.*v\([0-9\.]\+\).*/\1/g'
  ignore_errors: True
  register: helm_installed_version

- name: Download helm
  when: helm_version != helm_installed_version.stdout
  get_url:
    url: "https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz"
    dest: /tmp/helm.tar.gz

- name: Temp dir for helm
  when: helm_version != helm_installed_version.stdout
  file:
    path: /tmp/helm
    state: directory

- name: Unpack helm
  when: helm_version != helm_installed_version.stdout
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
    remote_src: yes

- name: Copy helm to /usr/local/bin
  become: True
  when: helm_version != helm_installed_version.stdout
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- shell: skaffold version | sed 's/.*v\([0-9\.]\+\).*/\1/g'
  ignore_errors: True
  register: skaffold_installed_version

- name: Install skaffold
  become: True
  when: skaffold_version != skaffold_installed_version.stdout
  shell: curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/v{{skaffold_version}}/skaffold-linux-amd64 && chmod +x /tmp/skaffold && mv /tmp/skaffold /usr/local/bin

- shell: tilt version | sed 's/.*v\([0-9\.]\+\).*/\1/g'
  ignore_errors: True
  register: tilt_installed_version

- name: Install tilt
  become: True
  when: tilt_version != tilt_installed_version.stdout
  shell: curl -fsSL https://github.com/windmilleng/tilt/releases/download/v{{tilt_version}}/tilt.{{tilt_version}}.linux.x86_64.tar.gz | tar -xzv tilt && mv tilt /usr/local/bin/tilt

- name: Install devspace bash completions
  become: True
  shell: curl -Lo /etc/bash_completion.d/devspace https://raw.githubusercontent.com/loft-sh/devspace/master/completion/bash.sh
