---
- name: Install git
  become: True
  apt: name=git state=latest

- stat: path=~/.gitconfig
  register: gitconfig

- name: Configure git
  when: not gitconfig.stat.exists
  shell: git config --global user.email "garton.tim@gmail.com" && git config --global user.name "Tim Garton" && git config --global push.default simple && git config --global core.editor vim

- name: Use git instead of https
  shell: git config --global url.git@github.com:.insteadOf https://github.com/

- name: Make default merge no-ff
  shell: git config --global merge.ff no

- name: Make default pull ff
  shell: git config --global pull.ff yes

- name: Make default conflict deff3
  shell: git config --global merge.conflictstyle diff3

- name: Add git-lfs key
  become: True
  apt_key: url='https://packagecloud.io/github/git-lfs/gpgkey'

- name: Add git-lfs repository
  become: True
  apt_repository: repo='deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main' state=present update_cache=yes

- name: Install git-lfs
  become: True
  apt: name=git-lfs state=latest

- name: Install git-lfs filters
  shell: git lfs install
