---
- stat: path=/usr/lib/jvm/java-7-oracle/jre/bin/java
  register: java

- name: Add java repo
  become: True
  when: not java.stat.exists
  apt_repository: repo='ppa:webupd8team/java'

- name: Apt update
  become: True
  when: not java.stat.exists
  apt: update_cache=yes

#- name: Accept java 7 license
#  become: True
#  when: not java.stat.exists
#  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

#- name: Install java 7
#  become: True
#  apt: name=oracle-java7-installer state=latest

- name: Accept java 8 license
  become: True
  when: not java.stat.exists
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install java 8
  become: True
  apt: name=oracle-java8-installer state=latest

- name: Apache Portable Runtime Library
  become: yes
  apt: name=libapr1-dev state=latest

- name: check gradle
  command: which gradle
  environment:
    PATH: /opt/gradle/bin
  ignore_errors: yes
  register: gradle_check

- name: download gradle
  when: gradle_check.rc != 0
  get_url:
    url: https://services.gradle.org/distributions/gradle-{{gradle_version}}-bin.zip
    dest: /tmp/gradle-bin.zip

- name: unpack gradle
  become: yes
  when: gradle_check.rc != 0
  unarchive: src=/tmp/gradle-bin.zip dest=/opt remote_src=yes

- name: link gradle
  become: yes
  file:
    src: /opt/gradle-{{gradle_version}}
    dest: /opt/gradle
    state: link
