---
- stat: path=/usr/bin/VBoxManage
  register: vbox

- name: virtualbox apt repository keys
  become: True
  when: not vbox.stat.exists
  apt_key: url={{item}}
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox.asc
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc

# These shouldn't be necessary, the apt_key module should handle it
#- name: Add virtualbox GPG key
#  become: True
#  when: not vbox.stat.exists
#  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys {{item}
#  with_items:
#    - 7B0FAB3A13B907435925D9C954422A4B98AB5139
#    - B9F8D658297AF3EFC18D5CDFA2F683C52980AECF

- name: virtualbox apt repository
  become: True
  when: not vbox.stat.exists
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{virtualbox_distribution_release}} contrib" state=present update_cache=yes

- name: accept virtualbox extensions license
  become: True
  debconf: name=virtualbox-ext-pack question=virtualbox-ext-pack/license value=true vtype=select

- name: install virtualbox
  become: True
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - virtualbox-5.2
    #- virtualbox-ext-pack #isn't from the virtualbox repo, so causes issues

- name: Add current user to vboxusers group
  become: True
  user: name={{ansible_user_id}} groups=vboxusers append=yes

- name: Add keyfile section to NetworkManager.conf
  become: True
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: '\[keyfile\]'
    line: '[keyfile]'

- name: Add unmanaged vboxnet0 to NetworkManager.conf
  become: True
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    insertafter: '\[keyfile\]'
    regexp: 'unmanaged-devices='
    line: 'unmanaged-devices=interface-name:vboxnet0'
