---
- name: Set HISTSIZE
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTSIZE=.*$'
    line: 'HISTSIZE=-1'

- name: Set HISTFILESIZE
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTFILESIZE=.*$'
    line: 'HISTFILESIZE=-1'

- name: Set HISTTIMEFORMAT
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTTIMEFORMAT=.*$'
    line: 'HISTTIMEFORMAT="%F %T "'

- name: Set PROMPT_COMMAND
  lineinfile:
    dest: ~/.bashrc
    regexp: 'export PROMPT_COMMAND=.*$'
    line: 'export PROMPT_COMMAND="history -a" #flush history after every command'

#- name: Create goenv function
#  lineinfile:
#    dest: ~/.bashrc
#    regexp: ^goenv.*
#    line: goenv() { TMPGOPATH="$(while [[ $PWD != "/" && ${PWD##*/} != "src" ]]; do cd ..; done && cd .. && pwd)"; GOPATH="$TMPGOPATH" PATH=$PATH:"$TMPGOPATH/bin" "$@"; }

#- name: Create goenv completion
#  lineinfile:
#    dest: ~/.bashrc
#    line: complete -F _command goenv

# Not sure this is actually necessary
- name: Export HISTFILESIZE HISTSIZE HISTTIMEFORMAT
  lineinfile: dest=~/.bashrc line='export HISTFILESIZE HISTSIZE HISTTIMEFORMAT'

- name: Create screen config
  copy: src=roles/user_config/files/screenrc dest=~/.screenrc mode=0600

#- name: Add git doglog
#  shell: git config --global alias.doglog "log --graph --pretty=format:'%h -%C(yellow)%d%Creset %C(bold white)%s%Creset %Cgreen(%cd) %C(bold blue)<%an>%Creset' --date=iso"

#- name: Add git pr
#  shell: git config --global alias.pr '!xdg-open "$(git remote -v | grep origin | grep push | cut -f 2 | cut -d " " -f 1 | sed -e "s|git@\(.*\):\(.*\).git|https://\1/\2|")/pull/new/$(git rev-parse --abbrev-ref HEAD)"'

- name: Set show dirty state
  lineinfile:
    dest: ~/.bashrc
    regexp: ^export GIT_PS1_SHOWDIRTYSTATE=.*
    line: export GIT_PS1_SHOWDIRTYSTATE=1

- name: Set git prompt
  lineinfile:
    dest: ~/.bashrc
    regexp: ^export PS1=.*
    line: export PS1='[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")]\$ '
