---
# Also could try things like this here:
#   gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 6
#   gsettings get org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize
#   gsettings list-keys org.compiz.wall:/
#   gsettings get org.gnome.Terminal.ProfilesList default

- name: Lookup gnome terminal default profile
  shell: gsettings get org.gnome.Terminal.ProfilesList default
  #shell: dconf read /org/gnome/terminal/legacy/profiles:/default
  register: profile

- shell: dconf write /org/gnome/settings-daemon/plugins/media-keys/terminal '"<Super>t"'
- shell: dconf write /org/gnome/terminal/legacy/keybindings/help '"disabled"'
- shell: dconf write /org/gnome/terminal/legacy/profiles:/:{{ profile.stdout }}/scrollback-unlimited true
- shell: dconf write /org/gnome/terminal/legacy/profiles:/:{{ profile.stdout }}/login-shell true
- shell: dconf write /org/gnome/terminal/legacy/profiles:/:{{ profile.stdout }}/visible-name '"Default"'

- shell: dconf write /desktop/unity/lenses/applications/display-available-apps false #don't show online results in dash
- shell: dconf write /desktop/unity/lenses/files/use-locate false #don't show file results
- shell: dconf write /com/canonical/unity/lenses/remote-content-search '"none"'
- shell: dconf write /com/canonical/indicator/power/show-percentage true
- shell: dconf write /com/canonical/unity/launcher/favorites "$(dconf read /com/canonical/unity/launcher/favorites | ruby -e 'items = eval(STDIN.read); items.delete("application://ubuntu-amazon-default.desktop"); p items')"

- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/show-launcher '"<Super>space"'
- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/execute-command '"<Super>r"'
- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/panel-first-menu '"Disabled"' #don't show application first menu on Alt-F10
- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/reveal-trigger 0
- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/reveal-pressure 1
- shell: dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode 1
- shell: dconf write /org/compiz/profiles/unity/plugins/core/hsize 4
- shell: dconf write /org/compiz/profiles/unity/plugins/core/vsize 1
- shell: dconf write /org/compiz/profiles/unity/plugins/wall/allow-wraparound true
- shell: dconf reset /org/compiz/profiles/unity/plugins/scale/initiate-key
#- shell: dconf write /org/compiz/profiles/unity/plugins/scale/initiate-key '"<Super>w"'
- shell: dconf reset /org/compiz/profiles/unity/plugins/expo/expo-key
#- shell: dconf write /org/compiz/profiles/unity/plugins/expo/expo-key '"<Super>s"'

- shell: dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized '["<Alt>F10"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right '["<Super>Right"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left '["<Super>Left"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up '["<Super>Up"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down '["<Super>Down"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left '["<Shift><Super>Left"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right '["<Shift><Super>Right"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-up '["<Shift><Super>Up"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-down '["<Shift><Super>Down"]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-1 '[""]'
- shell: dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 '[""]'

- shell: dconf write /org/gtk/settings/file-chooser/show-hidden true
- shell: dconf write /org/gnome/nautilus/preferences/default-folder-viewer '"list-view"'
