---
- name: docker apt repository key
  become: True
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=58118E89F3A912897C070ADBF76221572C52609D

- name: docker apt repository
  become: True
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main" state=present update_cache=yes

- name: make sure lxc-docker is not installed
  become: True
  apt: name=lxc-docker state=absent update_cache=yes cache_valid_time=600 purge=yes

- name: install docker-engine
  become: True
  apt: name=docker-engine state=latest update_cache=yes cache_valid_time=600

#- name: install pip
#  become: True
#  apt: name=python-pip state=latest update_cache=yes cache_valid_time=600

#- name: install docker-py module
#  become: True
#  pip: name=docker-py state=present version=1.7.0
