---
- stat: path=/usr/local/vim/bin/vim
  register: vim

- name: Install build dependencies
  become: True
  shell: apt-get -y build-dep vim-gtk

- name: Create dev dir
  file: path=~/dev state=directory

- name: Checkout vim source
  when: not vim.stat.exists
  git: repo=https://github.com/vim/vim.git dest=~/dev/vim

- name: Configure vim source
  when: not vim.stat.exists
  shell: ./configure --prefix=/usr/local/vim --enable-pythoninterp=yes --enable-python3interp=yes --enable-multibyte=yes --enable-cscope=yes --enable-rubyinterp=yes --with-ruby-command=/usr/local/rvm/rubies/default/bin/ruby chdir=~/dev/vim

- name: Compile vim source
  when: not vim.stat.exists
  shell: make chdir=~/dev/vim

- name: Install vim
  become: True
  when: not vim.stat.exists
  shell: make install chdir=/home/tim/dev/vim

- name: Install vim symbolic links
  become: True
  when: not vim.stat.exists
  shell: ln -s /usr/local/vim/bin/* /usr/local/bin

- name: Install vi symbolic link
  become: True
  when: not vim.stat.exists
  shell: ln -s /usr/local/vim/bin/vim /usr/local/bin/vi

- name: Checkout vimconfig
  git: repo=git@github.com:ralfthewise/vimconfig.git dest=~/dev/vimconfig force=no update=no

- name: Init vimconfig
  shell: ~/dev/vimconfig/init.sh
