---
# - name: Enable restricted source packages
#   become: True
#   notify:
#     - Update apt cache
#   lineinfile:
#     dest: /etc/apt/sources.list
#     regexp: '^# deb-src (.+) main restricted$'
#     backrefs: True
#     line: 'deb-src \1 main restricted'

# - name: Enable universe source packages
#   become: True
#   notify:
#     - Update apt cache
#   lineinfile:
#     dest: /etc/apt/sources.list
#     regexp: '^# deb-src (.+) universe$'
#     backrefs: True
#     line: 'deb-src \1 universe'

- name: Enable source, restricted and universe repositories
  ansible.builtin.deb822_repository:
    name: ubuntu-official-sources
    types: [deb, deb-src]
    uris: http://archive.ubuntu.com/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: [main, restricted, universe, multiverse]
    state: present
  become: True

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: True
