---
- stat: path=/usr/local/rbenv/bin/rbenv
  register: rbenv

- name: Install rbenv
  become: True
  when: not rbenv.stat.exists
  shell: |
    export RBENV_ROOT=/usr/local/rbenv
    export PATH=$RBENV_ROOT/bin:$PATH
    mkdir /usr/local/rbenv
    ln -s /usr/local/rbenv /root/.rbenv
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash

- name: Install system rbenv profile
  become: True
  copy: src=roles/rvm/files/rbenv.sh dest=/etc/profile.d/rbenv.sh group=root owner=root mode=0644

- name: Install ruby
  become: True
  when: not rbenv.stat.exists
  shell: bash -l -c 'rbenv install {{ruby_version}}'
