---
- stat: path=/usr/local/rbenv/bin/rbenv
  register: rbenv

- name: Install rbenv
  become: True
  when: not rbenv.stat.exists
  shell: |
    export RBENV_ROOT=/usr/local/rbenv
    export PATH=$RBENV_ROOT/bin:$PATH
    mkdir /usr/local/rbenv
    ln -sfn /usr/local/rbenv /root/.rbenv
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
    rbenv init -

- name: Install system rbenv profile
  become: True
  copy: src=roles/rbenv/files/rbenv.sh dest=/etc/profile.d/rbenv.sh group=root owner=root mode=0644

- name: Upgrade ruby-build to pull down new ruby builds
  become: True
  shell: git -C "$(rbenv root)"/plugins/ruby-build pull

- name: Install ruby
  become: True
  shell: bash -l -c 'rbenv versions --bare | grep -q {{ruby_version}} || rbenv install {{ruby_version}}'

- name: Set global default ruby version
  become: True
  shell: bash -l -c 'rbenv global {{ruby_version}}'

- name: Install updated bundler
  become: True
  shell: bash -l -c 'gem install bundler'
